name: ⚡ Get X.com Influencers Posts

on:
  repository_dispatch:
    types: [get-x-influencers-posts]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  get_x_influencers_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
        name: Install deps

      - run: npx playwright install --with-deps firefox
        name: Install Playwright browsers

      - name: Run bot
        env:
          DISCORD_TOKEN:   ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ vars.X_INFLUENCERS_CHANNEL_ID }}
          X_USERNAMES:     ${{ vars.X_INFLUENCERS_USERNAMES }}
          X_COOKIE_HEADER: ${{ vars.X_COOKIE_HEADER }}
        run: node twitter_influencers/index.mjs

      - name: Commit state
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase --autostash origin main
          shopt -s nullglob
          files=(twitter_influencers/last_link_*.json twitter_influencers/debug_*.html)
          if (( ${#files[@]} )); then
            git add "${files[@]}"
          fi
          git diff --cached --quiet || git commit -m "Update last seen links"
          git push
