name: 📻 Get the RSS News

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  read-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run rss bot
        env:
          DISCORD_TOKEN:   ${{ secrets.DISCORD_TOKEN }}
          NEWS_CHANNEL_ID: ${{ secrets.NEWS_CHANNEL_ID }}
          RSS_FEEDS:       ${{ vars.RSS_FEEDS }}
        run: node getrss.mjs

      - name: Commit updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rss-state.json
          git diff --cached --quiet || git commit -m "ci: update rss-state.json"
          git push
