name: 📸 Take CNN Fear & Greed Screenshot

on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        # this will pull down firefox (and others if you omit --with-deps)
        run: npx playwright install --with-deps firefox

      - name: Run screenshot bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID:    ${{ secrets.CHANNEL_ID }}
        run: node screenshot.js
