# .github/workflows/screenshot.yml
name: Screenshot → Discord

on:
  workflow_dispatch:
  schedule: 
    - cron: '*/15 * * * *'

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Firefox
        run: npx playwright install --with-deps firefox

      - name: Run screenshot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID:   ${{ secrets.CHANNEL_ID }}
        run: npm start
