
name: 👑 Super Pony Bot

on:
  repository_dispatch:
    types: [super_pony_bot] # Triggered by a repository dispatch event
  workflow_dispatch:

permissions:
  contents: write    # allow GITHUB_TOKEN to push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # if action is already running, cancel it
  
jobs:
  handle-users-commands:
    runs-on: ubuntu-latest
    steps:

      # 1) Checkout with full history and persist the token
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # full history so git push will work
          ref: main                # explicitly checkout `main`
          persist-credentials: true

      # 2) Setup & run your bot
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Super Pony bot
        env:
          DISCORD_TOKEN:   ${{ secrets.DISCORD_TOKEN }}
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN1 }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID }}
          BOT_CHANNEL_ID: ${{ vars.BOT_CHANNEL_ID }}
          GRAPHS_CHANNEL_ID: ${{ vars.GRAPHS_CHANNEL_ID }}
          ANTICIPATED_CHANNEL_ID: ${{ vars.X_EARNINGS_CAL_CHANNEL_ID }}

        run: node job_runner.mjs --job ./super_pony/index.mjs --timeout-min 239.9 --label super-pony
